### ISSUE TITLE
Game and Board should be singletons

### ISSUE THREAD

**Issue by Chuzzy** [Chuzzy/ultimate-monopoly-lua#1]
There is only ever one instance of Game and one instance of Board. Despite this, they both have a class defined for each of them. It would be a bit more performant if they were just singletons as it would consume less memory and method lookups would be faster.

**Comment by ItsPepperpot** [comment]
:shipit:

**Comment by Chuzzy** [comment]
Closed by https://github.com/Chuzzy/ultimate-monopoly-lua/commit/128cffd45e5fbecc3e77a21853ab01ed5b303e2f
